language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
jdk: openjdk8
install:
  - pip install .[dev]
script:
  - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - pytest
